export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART"
export const SORT_PRODUCTS = "SORT_PRODUCTS";
export const ADVANCED_SORT = "ADVANCED_SORT";
